### ISSUE TITLE
Could not initialize class com.sun.jersey.core.header.MediaTypes

### ISSUE THREAD

**Issue by summerm78** [jenkinsci/urltrigger-plugin#45]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.327
OS: Linux - 4.18.0-348.7.1.el8_5.x86_64
---
ace-editor:1.1
active-directory:2.25
ant:1.13
antisamy-markup-formatter:2.6
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
authorize-project:1.4.0
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
build-pipeline-plugin:1.5.8
build-user-vars-plugin:1.8
caffeine-api:2.9.2-29.v717aac953ff3
categorized-view:1.12
checks-api:1.7.2
cloudbees-disk-usage-simple:0.10
cloudbees-folder:6.17
command-launcher:1.6
conditional-buildstep:1.4.1
copyartifact:1.46.2
credentials:1055.v1346ba467ba1
credentials-binding:1.27
display-url-api:2.3.5
dropdown-viewstabbar-plugin:1.7
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
email-ext:2.86
envinject:2.4.0
envinject-api:1.8
extended-read-permission:3.2
extra-columns:1.25
font-awesome-api:5.15.4-5
git:4.10.1
git-client:3.10.1
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.4
gradle:1.37.1
handlebars:3.0.8
htmlpublisher:1.28
jackson2-api:2.13.1-244.v773c36c5b330
javadoc:1.6
jaxb:2.3.0.1
jdk-tool:1.5
jenkinswalldisplay:0.6.34
jjwt-api:0.11.2-9.c8b45b8bb173
jobConfigHistory:2.31-rc1098.b666422863b2
jobcopy-builder:1.4.2
join:1.21
jquery:1.12.4-1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
lockable-resources:2.13
mailer:1.34
matrix-auth:3.0
matrix-project:1.19
maven-plugin:3.16
momentjs:1.1.1
multiple-scms:0.8
naginator:1.18.1
nodelabelparameter:1.10.3
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.6.1
parameterized-trigger:2.43
performance:3.20
pipeline-build-step:2.15
pipeline-github-lib:1.0
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:427.va6441fa17010
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.20
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
pipeline-utility-steps:2.11.0
plain-credentials:1.7
plugin-usage-plugin:2.1
plugin-util-api:2.10.0
popper-api:1.16.1-2
popper2-api:2.11.0-1
rebuild:1.32
resource-disposer:0.17
run-condition:1.5
schedule-build:178.v32999348869c
scm-api:2.6.5
script-security:1118.vba21ca2e3286
slack:2.49
snakeyaml-api:1.29.1
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:308.v852b473a2b8c
test-results-analyzer:0.3.5
timestamper:1.15
token-macro:267.vcdaea6462991
trilead-api:1.0.13
uno-choice:2.5.7
urltrigger:0.50
windows-slaves:1.8
workflow-aggregator:2.6
workflow-api:1108.v57edf648f5d4
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-durable-task-step:1112.vda00e6febcc1
workflow-job:1145.v7f2433caa07f
workflow-multibranch:696.v52535c46f4c9
workflow-scm-step:2.13
workflow-step-api:615.vb09dac339255
workflow-support:804.vba10a18a1476
ws-cleanup:0.40
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Redhat Enterprise Linux 8.5

### Reproduction steps

After updateing Jenkins to 2.327 and all plugins to the newest versions, every time a URL-Trigger polls an error occures.

### Expected Results

URL-Trigger should work

### Actual Results

URL-Trigger gives the following error

Polling started on Jan 5, 2022, 9:40:00 AM
Polling for the job zt_tae_m
Looking nodes where the poll can be run.
Looking for a node to the restricted label zt_tae_m_label.

Polling remotely on zt_tae_m
Resolving environment variables using global values
[ERROR] - Polling error...
[ERROR] - Error message: Could not initialize class com.sun.jersey.core.header.MediaTypes

**Comment by slimmaalej** [comment]
also facing this issue 
Jenkins 2.319.1
2022-01-05 09:23:00.442+0000 [id=1424]  WARNING o.j.lib.xtrigger.AbstractTrigger#reportError: Polling failed
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jersey.core.header.MediaTypes
        at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:182)
        at com.sun.jersey.core.spi.factory.MessageBodyFactory.initReaders(MessageBodyFactory.java:176)
        at com.sun.jersey.core.spi.factory.MessageBodyFactory.init(MessageBodyFactory.java:162)
        at com.sun.jersey.api.client.Client.init(Client.java:343)
        at com.sun.jersey.api.client.Client.access$000(Client.java:119)
        at com.sun.jersey.api.client.Client$1.f(Client.java:192)
        at com.sun.jersey.api.client.Client$1.f(Client.java:188)
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
        at com.sun.jersey.api.client.Client.<init>(Client.java:188)
        at com.sun.jersey.api.client.Client.<init>(Client.java:171)
        at com.sun.jersey.api.client.Client.create(Client.java:683)
        at org.jenkinsci.plugins.urltrigger.URLTrigger.createClientWithoutProxy(URLTrigger.java:402)
        at org.jenkinsci.plugins.urltrigger.URLTrigger.createClient(URLTrigger.java:384)
        at org.jenkinsci.plugins.urltrigger.URLTrigger.getClientObject(URLTrigger.java:364)
        at org.jenkinsci.plugins.urltrigger.URLTrigger.checkIfModifiedEntryForHttpOrHttpsURL(URLTrigger.java:287)
        at org.jenkinsci.plugins.urltrigger.URLTrigger.checkIfModifiedEntry(URLTrigger.java:279)
        at org.jenkinsci.plugins.urltrigger.URLTrigger.checkIfModified(URLTrigger.java:254)
        at org.jenkinsci.lib.xtrigger.AbstractTrigger$Runner.run(AbstractTrigger.java:212)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by piesarmin** [comment]
Update Jackson API Plugin (2.13.1-244.v773c36c5b330) seems to be the problem.

**Comment by basil** [comment]
Incremental build 0.51-rc275.eb29116478fc of `urltrigger` (containing jenkinsci/urltrigger-plugin#46) is available for testing. The incremental build is available from: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/urltrigger/0.51-rc275.eb29116478fc/

To test the incremental build of `urltrigger`, you must also install:

- Release 2.13.1-246.va8a9f3eaf46a of `jackson2-api` from: https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/jackson2-api/2.13.1-246.va8a9f3eaf46a/
- Release 2.35-2 of `jersey2-api` from: https://repo.jenkins-ci.org/artifactory/public/io/jenkins/plugins/jersey2-api/2.35-2/
- Release 4.5.13-1.0 of `apache-httpcomponents-client-4-api` from: https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/apache-httpcomponents-client-4-api/4.5.13-1.0/

@piesarmin @slimmaalej @summerm78 Can you please test the `urltrigger`, `jackson2-api`, `jersey2-api`, and `apache-httpcomponents-client-4-api` releases mentioned above and confirm the issue is resolved? For instructions on how to install a custom build, see: https://www.jenkins.io/doc/book/managing/plugins/#advanced-installation

**Comment by piesarmin** [comment]
Hi Basil,

> Incremental build 0.51-rc276.c4687fe3ec63 of `urltrigger` (containing #46) is available for testing. The incremental build is available from: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/urltrigger/0.51-rc276.c4687fe3ec63/
> 
> To test the incremental build of `urltrigger`, you must also install:
> 
> * Release 2.13.1-246.va8a9f3eaf46a of `jackson2-api` from: https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/jackson2-api/2.13.1-246.va8a9f3eaf46a/
> * Release 2.35-3 of `jersey2-api` from: https://repo.jenkins-ci.org/artifactory/public/io/jenkins/plugins/jersey2-api/2.35-3/
> * Release 4.5.13-1.0 of `apache-httpcomponents-client-4-api` from: https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/apache-httpcomponents-client-4-api/4.5.13-1.0/
> 
> @piesarmin @slimmaalej @summerm78 Can you please test the `urltrigger`, `jackson2-api`, `jersey2-api`, and `apache-httpcomponents-client-4-api` releases mentioned above and confirm the issue is resolved? For instructions on how to install a custom build, see: https://www.jenkins.io/doc/book/managing/plugins/#advanced-installation

The following versions work for me (Jenkins 2.319.1, Windows):
* Jackson 2 API Plugin  2.13.1-246.va8a9f3eaf46a
* Jenkins Apache HttpComponents Client 4.x API Plugin  4.5.13-1.0
* Jersey 2 API  2.35-3
* Jenkins URLTrigger Plug-in  **0.50**

Installing URLTrigger 0.51-rc276.c4687fe3ec63 leads to

```
[ERROR] - Polling error...
[ERROR] - Error message: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=US-ASCII, type=class org.glassfish.jersey.client.ClientResponse, genericType=class org.glassfish.jersey.client.ClientResponse.
[ERROR] - Error cause: MessageBodyReader not found for media type=text/plain;charset=US-ASCII, type=class org.glassfish.jersey.client.ClientResponse, genericType=class org.glassfish.jersey.client.ClientResponse.
```

**Comment by slimmaalej** [comment]
same error when installing 0.51-rc276

**Comment by basil** [comment]
@piesarmin @slimmaalej @summerm78 Can you try 0.51-rc277.6d82e923c55d? https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/urltrigger/0.51-rc277.6d82e923c55d/

**Comment by slimmaalej** [comment]
works fine at least no errors anymore

**Comment by piesarmin** [comment]
works for me, too :)

**Comment by basil** [comment]
Great news! If you could go ahead and approve #46 (or at least mention that you have tested the PR and it works), then that would hopefully give the maintainer of this plugin confidence in merging and releasing it.

**Comment by summerm78** [comment]
Thank you for the fix. Since this is a production system, I can't restart it until the weekend. I'll test it then and provide you feedback.

**Comment by summerm78** [comment]
It worked for me too.

**Comment by TonyNoble** [comment]
Thanks for everyone's help - released as urltrigger-0.51
